mysql:
  image: mysql:5.6.26
  environment:
    MYSQL_ROOT_PASSWORD: 'pass'
  ports:
    - '3306:3306'

nginx:
  build: Dockerfiles/nginx
  ports:
    - '80:80'
  links:
    - web

web:
  build: .
  command: bundle exec unicorn -c config/unicorn.rb
  volumes:
    - .:/usr/src/app
  ports:
    - '3000:3000'
  links:
    - mysql
  environment:
    RAILS_ENV: development
    MYSQL_ROOT_PASSWORD: 'pass'
    DATABASE_URL: mysql2://root:pass@mysql:3306
    SECRET_KEY_BASE: hogehoge
    MAILER_DEFAULT_URL: '192.168.99.100:3000'
    MAIL_SERVER_ADDRESS: 'please fill here'
    MAIL_SERVER_DOMAIN: 'please fill here'
    MAIL_USER_NAME: 'please fill here'
    MAIL_USER_PASS: 'please fill here'
